### ISSUE TITLE
message when selecting filters for lexicon

### ISSUE THREAD

**Issue by flaviavenerabile** [klab-ilc-cnr/Maia#10]
As title, when selecting one of the values in a menù for filtering search, the following error message appears: Http failure response for https://klab.ilc.cnr.it/maia-compl-it-be-new/maia/lexo/lexicon/data/lexicalEntries: 500 OK

**Comment by MPapini91** [comment]
@flaviavenerabile Trying to replicate the bug turns out to occur only when filtering by type. Do you confirm the analysis? Alternatively please provide a description by steps.

**Comment by MPapini91** [comment]
`400 : "type field must be one of [, word, etymon, cognate, multi-word expression, affix]"`

Check the values passed with the Type field. Check how the select is populated and align it with the expected values from the back-end. Also check the value passed in the http request that seems to be fixed at entry (planted in the code?).

**Comment by MPapini91** [comment]
@andreabellandi, from which service can I retrieve the list [, word, etymon, cognate, multi-word expression, affix]? Currently, the type filter is being populated with ontolex/data/lexicalEntryType values but is not correct for all types (for example, it contains "lexical entry" which is not a valid filter).

Andrea, da quale servizio posso recuperare l'elenco [, parola, etimo, cognato, espressione multiparola, affisso]? Attualmente, il filtro del tipo viene popolato con i valori ontolex/data/lexicalEntryType, ma non è corretto per tutti i tipi (ad esempio, contiene "voce lessicale" che non è un filtro valido).

![Image](https://github.com/klab-ilc-cnr/Maia/assets/61142119/fb9f083d-d47e-43b8-8d73-7fafd52adda4)
