### ISSUE TITLE
bugged text window scrolling behavior

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/Maia#100]
depending on the text window size, sometimes it's possibile to scroll only up or down, since the right handle stay attached to the upper (or lower) border. In the screenshot, for example, it is not possible to scroll up

![image](https://github.com/klab-ilc-cnr/Maia/assets/55898315/df314bcc-473b-4a60-857e-ae95235159be)

**Comment by cienco** [comment]
Sarebbe utile poter avere questo stesso testo in develop per fixare questo e altri bug, o uno equivalente, in cui ci sono i numeri di riga nel sentum e le righe sono molto brevi come in questo caso
