### ISSUE TITLE
annotation column of text window should be open by default

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/Maia#101]
As title: each time a user selects a text in the corpus explorer and opens up a text window, the rightmost column of that window, relative to "Annotation", should appear open by default

**Comment by MPapini91** [comment]
Mantenere nel codice la gestione booleana dello stato di apertura in quanto si prevede una futura memorizzazione dello stato a back-end (vedi issue #103 )

**Comment by cienco** [comment]
> As title: each time a user selects a text in the corpus explorer and opens up a text window, the rightmost column of that window, relative to "Annotation", should appear open by default

In the specification sheet was stated the opposite, it should be closed as it is now. Do you want to change the spec?

**Comment by magoafono** [comment]
Yes, please change the behaviour as described before.
This default setting is intended to mitigate the text editor reflow problem (like #110 , #108)
