### ISSUE TITLE
double clic for text annotation should not select whitespaces following the selected word

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/Maia#102]
As title. 

Current behavior on double clic:

![image](https://github.com/klab-ilc-cnr/Maia/assets/55898315/05529883-3441-4fac-af82-88936a956151)

Expected behavior on double clic:

![image](https://github.com/klab-ilc-cnr/Maia/assets/55898315/44f3269c-61ce-46dc-9841-58e512d7cc91)

The problem appears in Windows, independently from the used browser. However, for Linux users the behavior is already the expected one.

**Comment by cienco** [comment]
Apparently this is a window "feature". This is a problem that affects probably only window users. I fixed it with a workaround. Anyway you can also use the trick that is showed in one of the answers in this page
https://superuser.com/questions/282568/is-there-a-way-to-not-select-whitespace-after-a-word-when-double-clicking
