### ISSUE TITLE
Errore durante il filtro dei risultati di una ricerca

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#105]
Nel caso di filtraggio dei risultati tramite il campo "Testo" si ottiene il seguente errore nella console dell'interfaccia:
Failed to load resource: the server responded with a status of 500 ()

Vedendo il log di texto si vede questo errore:

it.cnr.ilc.texto.controller.Controller   : (simone) [] kwic query "token = 'oriente'" filter "resource_name like 'deca%'" index out of bounds

La conseguenza è che la finestra di ricerca rimane in attesa indefinita

Come si è generato l'errore:
1 - Effettuare la ricerca della parola "oriente" senza selezionare nessun file del corpus
2 - spostarsi nell'ultima pagina dei risultati
3 - filtrare i risultati per "Testo" mettendo come value "deca"

**Comment by MPapini91** [comment]
Lato interfaccia il problema sembra essere legato ai valori start ed end passati nel payload della richiesta. In particolare nel caso in esempio si richiede:
`{"searchMode":"form","searchValue":"oriente","contextLength":5,"index":null,"kwic":null,"leftContext":null,"rightContext":null,"text":"deca","reference":null},"start":100,"end":110}`
Eseguendo direttamente la ricerca sul solo Decameron di "oriente" vediamo però che i risultati sono 6. 
In caso di modifica dei filtri è necessario ripetere la ricerca con indice start 0, indipendentemente dalla pagina corrente.

**Comment by davide-albanesi-ilc** [comment]
Quello che dice Mafalda è esatto: quando si effettua una modifica ai filtri i risultati presumibilmente cambieranno e non è possibile sapere a priori se tra 100 e 110 con il nuovo filtro ci saranno dati, è quindi necessario impostare start a 0.
