### ISSUE TITLE
Annotazione fantasma

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#106]
Nel pannello Text, avendo un layer selezionato e visibile, se io seleziono una parola e clicco su una annotazione già esistente e ripeto il passaggio, viene renderizzata un'annotazione inesistente (per gli step precisi si faccia riferimento al pdf). Il test è stato eseguito sul branch di develop, collegato alla 234 e utilizzando il browser Chrome.

[Bug_annotazione_fantasma.pdf](https://github.com/klab-ilc-cnr/Maia/files/15304843/Bug_annotazione_fantasma.pdf)

**Comment by cienco** [comment]
Ci sono delle problematiche legate all'attuale gestione delle annotazioni, con bug che spaziano dal frontend al backend, sarà necessaria un'analisi un po più approfondita appena possibile cercherò di elencare i punti critici. Per ora le problematiche legate alle annotazioni le lascerò un attimo da parte.

**Comment by cienco** [comment]
dovrebbero essere risolte con il rilascio di #117
