### ISSUE TITLE
Double annotation

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#107]
Nel momento in cui vado a inserire un'annotazione, talvolta a seguito del salvataggio la renderizzazione mostra due annotazioni dello stesso tipo sulla porzione di testo. Ricaricando la pagina la visualizzazione viene corretta. Non sembrano esserci pattern chiari che conducano all'errore.

**Comment by cienco** [comment]
dovrebbero essere risolte con il rilascio di #117
