### ISSUE TITLE
Loop of Texto on layer selection

### ISSUE THREAD

**Issue by flaviavenerabile** [klab-ilc-cnr/Maia#111]
Good evening everyone, I am writing to report an issue on Texto. 

The steps to get to the error follow:
1) I uploaded a file to ‘Corpus’;
2) I selected the file ‘BerakhotEstr2’ from the ‘Flavia_test’ folder with a double click;
3) In the Text window, I selected ‘Lexicon’ (previously created from my workspace) from the layer menu; then I selected the same ‘Lexicon’ layer from visibility. 
From this moment on, it loops and does not allow me to move forward.
I attach here a screen of the loop and the console error.

![Screenshot 2024-05-21 173614](https://github.com/klab-ilc-cnr/Maia/assets/63344692/8e79d3fc-2e64-440c-9744-247b58b695d0)
![Screenshot 2024-05-21 182637](https://github.com/klab-ilc-cnr/Maia/assets/63344692/40ff30b2-735e-403c-b4d5-e78db7385112)

**Comment by MPapini91** [comment]
Il caso in oggetto è relativo a un testo formato da una sola riga, quindi un caso limite che sembra coinvolgere sia interfaccia (@cienco ) che back-end (@davide-albanesi-ilc ).
Abbiamo fatto un controllo da interfaccia e risulta un possibile disallineamento con gli indici di start ed end rispetto a quanto memorizzato in TextO. In particolare, in apertura vediamo le chiamate:
GET `/maia-dev-2/maia/texto/resource/20085945/rowCount`
Response: 0

POST `/maia-dev-2/maia/texto/util/resource/20085945/rows`
Payload: `{"start":0,"end":1}`
Response: 
```
{
    "count": 1,
    "start": 0,
    "end": 1,
    "data": [
        {
            "id": 20085946,
            "index": null,
            "absolute": 0,
            "relative": null,
            "start": 0,
            "end": 3529,
            "text": "Da quando si [...]"
        }
    ]
}
```

Quando viene selezionato il layer in visualizzazione (indipendentemente da quale sia), abbiamo:
POST `/maia-dev-2/maia/texto/util/resource/20085945/rows`
Payload: `{"start":0,"end":0}`
Response: `{"count":1,"start":0,"end":0,"data":[]}`

POST `/maia-dev-2/maia/texto/util/resource/20085945/annotations`
Payload:` {"start":0,"end":0,"layers":[20085947]}`
Response: []

Esistono probabilmente due problemi:

1. il back-end restituisce un conteggio di righe pari a 0 quando esiste almeno 1 riga
2. il front-end non riesce a gestire il caso di testi senza righe (caso limite, esempio un testo vuoto)

**Comment by davide-albanesi-ilc** [comment]
In TextO a bug in rowCount service has been fixed
