### ISSUE TITLE
Error in rendering on Firefox

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#116]
Opening the Decameron on Chrome (Version 125.0.6422.77) and Firefox (Version 124.0.2) (same deploy, file and account), we see that on Firefox “Proemio” at the close of the first paragraph is cut off in rendering the text. This does not happen for all panel widths; in the example image the panel has been reduced to the minimum width on both browsers.

############################################################

Aprendo il Decameron su Chrome (Version 125.0.6422.77) e Firefox (Versione 124.0.2) (stesso deploy, file e account), vediamo che su Firefox "Proemio" in chiusura del primo paragrafo viene tagliato nella renderizzazione del testo. Questo non avviene per tutte le ampiezze del pannello, nell'immagine d'esempio il pannello è stato ridotto alla larghezza minima su entrambi i browser.

![image](https://github.com/klab-ilc-cnr/Maia/assets/61142119/20496b41-2830-46db-af16-3654e878da29)

**Comment by cienco** [comment]
Questo è un comportamento normale e corretto da parte della finestra di testo che renderizza i dati calcolando lo spazio disponibile. Lo spazio può variare a seconda del browser, o anche usando lo stesso browser con temi personalizzati e quindi deve essere calcolato dinamicamente.

**Comment by MPapini91** [comment]
> Questo è un comportamento normale e corretto da parte della finestra di testo che renderizza i dati calcolando lo spazio disponibile. Lo spazio può variare a seconda del browser, o anche usando lo stesso browser con temi personalizzati e quindi deve essere calcolato dinamicamente.

No, mi devo essere spiegata male, non è questione di ricalcolo dello spazio, è che viene proprio tagliata una stringa (anche dopo la PR legata a #117 .
Se confronti le due immagini vedrai che la prima riga di testo in un caso termina con Proemio, mentre nell'altro lo taglia

**Comment by MPapini91** [comment]
Workaround issue #138
