### ISSUE TITLE
Errore ricerca forma ad alta frequenza

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#119]
Abbiamo riscontrato un problema nella ricerca KWIC, in particolare cercando "il" sul deploy di develop otteniamo un errore di back-end (@davide-albanesi-ilc dovresti verificare perché riceviamo un errore 502). A livello di interfaccia, però, rimane bloccato con il loading in corso, cosa che non dovrebbe accadere, dovrebbe essere nascosto il loading e mostrato un messaggio di errore.
Il codice sembra essere quello relativo a workspace-search-tile ln 242:
this.searchService.search(this.searchRequest).subscribe(result => {
      this.searchResults = result.data;
      this.searchResults.forEach(res => res.id ? res.id : res.id = `id_${res.index}`);
      this.loading = false;
      this.totalRecords = result.count;
      this.updateTableHeight();
    });

In questo caso noto anche che non è stata gestita la subscription, né eventuali errori, si suggerisce di inserire

this.searchService.search(this.searchRequest).pipe(
take(1) oppure takeUntil(...),
catchError((error: HttpErrorResponse) => this.common. etc (vedi esempi in altri punti del codice)
)
.subscribe(result => {
      this.searchResults = result.data;
      this.searchResults.forEach(res => res.id ? res.id : res.id = `id_${res.index}`);
      this.loading = false;
      this.totalRecords = result.count;
      this.updateTableHeight();
    });

![Immagine WhatsApp 2024-06-04 ore 13 13 56_e957636f](https://github.com/klab-ilc-cnr/Maia/assets/61142119/a5a97aa9-7e87-4ac9-a842-c2182f89b8a5)

**Comment by magoafono** [comment]
@davide-albanesi-ilc ho verificato che la query specifica viene correttamente eseguita ma impiega circa 1 min e 30 sec. Potrebbe essere questo un problema (magari causato da un timeout)?

**Comment by cienco** [comment]
ho fatto una pull request per quanto riguarda la mia parte di modifiche
