### ISSUE TITLE
Overlapping of windows

### ISSUE THREAD

**Issue by flaviavenerabile** [klab-ilc-cnr/Maia#12]
When the Lexicon window is expanded, the editor window for an entry does not overlap. To view it, it is necessary to reduce size of the Lexicon window.

In some cases, the issue occurs with the following steps:

Opening the Lexicon window
Opening the editor
Clicking anywhere on the screen
The editor disappears
Subsequent clicks on other entries do not display them.
![issue3](https://github.com/klab-ilc-cnr/Maia/assets/63344692/663fa69a-a37b-48d8-b9d6-669f20493e10)
![issue3-1](https://github.com/klab-ilc-cnr/Maia/assets/63344692/864e6c85-c8af-418e-897f-1d6e24de0b10)

This also happens when clicking on a new entry without closing the window of a previously opened entry.

**Comment by MPapini91** [comment]
Couldn't replicate
