### ISSUE TITLE
Dictionary Editor - I attestazione in Boccaccio

### ISSUE THREAD

**Issue by CosBurg** [klab-ilc-cnr/Maia#120]
Dictionary Editor > I attestazione in Boccaccio

Dal menù a tendina eliminare il primo item = Opere volgari Boccaccio

![Screenshot_4-6-2024_162143_klab ilc cnr it](https://github.com/klab-ilc-cnr/Maia/assets/157484203/b633979a-7bf3-4126-bf25-9ff53911992a)

**Comment by MPapini91** [comment]
@davide-albanesi-ilc questa è la lista del servizio n 20

**Comment by davide-albanesi-ilc** [comment]
Creato servizio dictionary/authorDocuments

**Comment by MPapini91** [comment]
Fixed with commit 17918e6d194939e01dac842f439578cc35eeada2
