### ISSUE TITLE
Dictionary Editor - Occ. altre opere

### ISSUE THREAD

**Issue by CosBurg** [klab-ilc-cnr/Maia#121]
Dictionary Editor > Occ. altre opere:

Dal menù a tendina eliminare due item = _![Screenshot_4-6-2024_162633_klab ilc cnr it](https://github.com/klab-ilc-cnr/Maia/assets/157484203/e26c8735-10da-4060-8989-004d9b31d5f5)_ e _Decameron_

**Comment by MPapini91** [comment]
@davide-albanesi-ilc questa è la lista del servizio n 24

**Comment by davide-albanesi-ilc** [comment]
Fatto!

**Comment by MPapini91** [comment]
Fixed with commit 17918e6d194939e01dac842f439578cc35eeada2
