### ISSUE TITLE
Dictionary Editor - Creazione campo "Occorrenze totali"

### ISSUE THREAD

**Issue by CosBurg** [klab-ilc-cnr/Maia#122]
Rispetto al modello di voce che hanno mandato da Siena, allo stato attuale nel Dictionary Editor risulta mancare il campo "Occorrenze totali": si tratta di un campo che registra semplicemente un valore numerico, non testuale, relativo al numero delle occorrenze totali di una voce in Boccaccio (Decameron + altre opere). Per il momento questo numero va calcolato a mano, né avendo annotato il _Decameron_ né avendo fisicamente le altre opere nel corpus.
Allego il Word della voce modello che hanno mandato da Siena (con le nostre annotazioni di qualche riunione fa)
![Screenshot_4-6-2024_164144_docs google com](https://github.com/klab-ilc-cnr/Maia/assets/157484203/d42f352f-1b28-4485-a2af-a5d0823e6f0e)

**Comment by MPapini91** [comment]
Fixed with commit f4bbb902dfef14943522392a588d0c89bf297714
