### ISSUE TITLE
Dictionary Editor - Creazione campo "Occorrenze Decameron"

### ISSUE THREAD

**Issue by CosBurg** [klab-ilc-cnr/Maia#123]
Rispetto al modello di voce che hanno mandato da Siena, allo stato attuale nel Dictionary Editor risulta mancare il campo "Occorrenze _Decameron_": si tratta di un campo che registra un valore semplicemente numerico, relativo al numero delle occorrenze (token) di una voce nel _Decameron_. Per ora questo numero va calcolato e inserito a mano, non avendo ancora il _Decameron_ annotato.
Allego il Word con il modello di voce (con le nostre note di qualche riunione passata)
![Screenshot_4-6-2024_164144_docs google com](https://github.com/klab-ilc-cnr/Maia/assets/157484203/13bb2eed-6bc3-450c-b88f-c6c9dbdedcb2)

**Comment by MPapini91** [comment]
Per la persistenza utilizzare le note

**Comment by MPapini91** [comment]
Fixed with commit f4bbb902dfef14943522392a588d0c89bf297714
