### ISSUE TITLE
Dictionary Editor - I attestazione in Boccaccio - box testuale

### ISSUE THREAD

**Issue by CosBurg** [klab-ilc-cnr/Maia#124]
Dictionary Editor > I attestazione in Boccaccio:

Per questo campo, bisognerebbe aggiungere a lato un box di testo per inserire a mano il riferimento topografico dell'opera relativa.
Per esempio, nel modello di voce MALCONTENTO (allegato), il campo "I att." registra l'opera _Filostrato_ insieme al riferimento topografico [= pt. 8, ott. 31, v. 6.]. Ovviamente, se avessimo tutte le opere di Boccaccio strutturalmente e testualmente marcate/annotate il dato sarebbe importabile in automatico; per il momento servirebbe segnarlo a mano.

![Screenshot_4-6-2024_164144_docs google com](https://github.com/klab-ilc-cnr/Maia/assets/157484203/bbbd5f9f-0bc3-48fe-b631-1b244d8efb19)

**Comment by MPapini91** [comment]
@CosBurg il riferimento topografico deve essere formattato (corsivo, font particolari, etc) o no?

**Comment by CosBurg** [comment]
Non è necessaria alcuna formattazione
________________________________
Da: Mafalda Papini ***@***.***>
Inviato: mercoledì 5 giugno 2024 10:25
A: klab-ilc-cnr/Maia ***@***.***>
Cc: CosBurg ***@***.***>; Mention ***@***.***>
Oggetto: Re: [klab-ilc-cnr/Maia] Dictionary Editor - I attestazione in Boccaccio - box testuale (Issue #124)


@CosBurg<https://github.com/CosBurg> il riferimento topografico deve essere formattato (corsivo, font particolari, etc) o no?
