### ISSUE TITLE
SEARCH KWIC - Punteggiatura impropria immediatamente prima della keyword

### ISSUE THREAD

**Issue by CosBurg** [klab-ilc-cnr/Maia#127]
SEARCH KWIC:

i segni di interpunzione di poco precedenti nella stessa frase risultano impropriamente duplicati immediatamente prima della keyword cercata, come da immagine:

![Immagine 2024-06-07 143153](https://github.com/klab-ilc-cnr/Maia/assets/157484203/43aa94c5-1242-4f02-b670-f77496801666)

**Comment by MPapini91** [comment]
![Immagine WhatsApp 2024-06-07 ore 15 40 37_2f46d52b](https://github.com/klab-ilc-cnr/Maia/assets/61142119/ae8abde2-445d-4704-ad93-78ff9bb75ec2)


@cienco da una verifica la risposta di back-end risulta corretta, tuttavia sembra che il problema sia causato dalla direction in workspace-search-tile.component.scss ln 27 e seguenti:

```
.leftContext {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
  direction: rtl;
}
```

Pur risolvendo il problema del troncamento della stringa su resize della colonna, causa uno spostamento indesiderato della punteggiatura.
