### ISSUE TITLE
Duplicates in search results

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#132]
Ricercando la forma "raum*" (ma anche la forma "raumiliarla") otteniamo una serie di risultati duplicati. 

![Immagine WhatsApp 2024-06-25 ore 11 20 34_eacdd3cd](https://github.com/klab-ilc-cnr/Maia/assets/61142119/ec1b36e1-84bc-4118-af91-807b321dab55)
![Immagine WhatsApp 2024-06-25 ore 11 21 45_06566d3d](https://github.com/klab-ilc-cnr/Maia/assets/61142119/25e44d2a-d468-4fe6-b80c-d399a65732d4)

**Comment by davide-albanesi-ilc** [comment]
Bug corretto
