### ISSUE TITLE
Unexpected behavior updating annotation feature

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#139]
Verificando lo stato della segnalazione #73 abbiamo notato che, lavorando su layer con più feature, alla modifica del valore di una feature il sistema invoca talvolta il solo update, talvolta l'update del campo modificato e il create di tutte le altre feature. Questo comportamento potrebbe creare inconsistenze nei dati, è necessario eseguire una verifica. 
L'alternanza dei comportamenti non pare legata ai dati passati, in quanto eseguendo più volte il salvataggio senza modifiche allo stesso payload corrispondono comportamenti diversi.

**Comment by MPapini91** [comment]
@cienco questo è un problema che sarebbe opportuno analizzare insieme visto che abbiamo lavorato entrambi su quella parte di codice.

**Comment by cienco** [comment]
Si quello è il comportamento attuale ma per quanto mi riguarda non è necessario che funzioni così, da capire anche se ci sono motivi di backend per cui era stato fatto in questo modo. Il problema #73 credo non sia più presente
