### ISSUE TITLE
Errato posizionamento della finestra del testo al doppio click su di un KWIC

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#142]
Al click di una occorenza di ricerca nel KWIC può succedere che il testo non sia aperto alla posizione corretta.
Passi per ricreare l'errore:
1 - cercare guadagn*
2 - doppio click sulla riga con Ref II.9.51
3 - verificare il primo paragrafo visualizzato nella finestra del testo.

TO BE VERIFIED!

**Comment by MPapini91** [comment]
Da ulteriori verifiche risulta che il problema si presenti ridimensionando il pannello Text dopo la sua prima apertura, in quanto non vengono aggiornate le dimensioni utilizzate per il calcolo dello scroll. Per replicare: 

1. cercare guadagn*
2. doppio click sulla riga con Ref II.9.51
3. verificare il primo paragrafo visualizzato nella finestra del testo
4. modificare le dimensioni del pannello Text
5. doppio click su Ref. III.10.3
6. controllare il primo paragrafo calcolato
