### ISSUE TITLE
Error retrieving annotation data

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#144]
Abbiamo identificato una casistica nella quale l'editor del testo non riesce a recuperare le informazioni di annotazioni esistenti. Gli step per replicare sono:

1. inserire una annotazione su una parola con feature valorizzate (per esempio, layer Sintassi, etc) e salvare
2. fare doppio click su un altro termine nel testo
3. cliccare sull'etichetta dell'annotazione precedentemente inserita

Comportamento atteso --> viene riconosciuta l'annotazione esistente e ne sono visualizzati i dati
Comportamento attuale --> non riconosce neanche la presenza di una annotazione ma mantiene la precedente selezione (vedi figura)

![image](https://github.com/klab-ilc-cnr/Maia/assets/61142119/906b3355-5bf4-4681-a242-8465cadd4160)

**Comment by cienco** [comment]
non riesco a riprodurre il problema @MPapini91 puoi riprovare e vedere se c'è ancora?

**Comment by MPapini91** [comment]
@cienco  ho appena eseguito il test sul branch develop con macchina 207 e ho replicato:

1. apri il testo Filocolo (cartella Boccaccio)
2. seleziona il layer Semantica
3. scroll down fino alla riga 58 dove hai una annotazione su "cessata"
4. click su etichetta sopra "cessata" --> visualizza l'annotazione
5. doppio click su altra parola come per annotare (ma non ho annotato)
6. click su etichetta sopra "cessata" --> mantiene la selezione precedente e non visualizza i dati dell'annotazione
