### ISSUE TITLE
Lexicon window can disappear (partially) under main menu bar.

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#19]
The Lexicon window (but all windows in general) can disappear under main menu bar when someone move it using its handle (the title bar).
Step to reproduce it:
1 - log into maia
2 - select a workspace
3 - open Lexicon window
4 - attach the window to the middle magnet anchor
5 - extend lexicon window till the lover limit of the panel
6 - reduce the browser height
7 - move the lexicon window
8 - the window title bar (and the handle) disappears
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/fce2cf81-bf40-4fd5-9872-4d2977643b79)
The top attribute of the lexiconTile div is negative:
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/24680f57-3eb8-49ff-967d-07f17a8686af)

**Comment by cienco** [comment]
@magoafono which browser are you using? I am not able to reproduce the problem with chrome or firefox or edge
