### ISSUE TITLE
Text Editor not working on Firefox

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#20]
Using Firefox, text and annotations are not properly displayed. 

<img width="1281" alt="image" src="https://github.com/klab-ilc-cnr/Maia/assets/61142119/b36f716a-5990-43d6-97ce-440e91eaa8b5">

**Comment by MPapini91** [comment]
Linked to #28

**Comment by cienco** [comment]
not happening on last versione of firefox on widnows
