### ISSUE TITLE
Fix annotation delete

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#3]
Deleting an annotation does not work. Correct the behavior as soon as the deletion policy is decided.

**Comment by davide-albanesi-ilc** [comment]
Now an annotation can be removed even if it has features.

**Comment by MPapini91** [comment]
Eseguito test lato interfaccia, la rimozione avviene correttamente, tuttavia si hanno successivi errori nel recupero delle annotazioni su quella porzione di testo. In particolare, sulla macchina 207, vediamo:

**Comment by MPapini91** [comment]
@davide-albanesi-ilc ho appena fatto un controllo e sembra funzionare anche nel recupero delle annotazioni, hai per caso fatto degli interventi?

**Comment by davide-albanesi-ilc** [comment]
> @davide-albanesi-ilc ho appena fatto un controllo e sembra funzionare anche nel recupero delle annotazioni, hai per caso fatto degli interventi?

Sì corretto e aggiornato

**Comment by MPapini91** [comment]
La cancellazione di una annotazione è nuovamente bloccata
{
    "timestamp": "2024-07-16T09:28:27.246+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "500 : \"{\"timestamp\":\"2024-07-16T09:28:27.238+00:00\",\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/texto/annotation/20106493/remove\"}\"",
    "path": "/maia/texto/annotation/20106493/remove"
}

Nel back-end risulta
java.sql.SQLIntegrityConstraintViolationException: (conn=39651) Duplicate entry '20106514-2-2024-07-15 15:40:08' for key 'PRIMARY'
