### ISSUE TITLE
Issue about repositioning of a window

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#35]
The system moves a window whose header would have disappeared below the main toolbar to the top left corner. The expected behavior is to automatically move the window in question only vertically.

Il sistema sposta nell'angolo in alto a sinistra una finestra la cui intestazione sarebbe scomparsa al di sotto della toolbar principale. Il comportamento atteso è quello di spostare automaticamente la finestra in questione solo verticalmente.

**Comment by MPapini91** [comment]
Linked to #19

**Comment by MPapini91** [comment]
It will not be fixed because it is a compromise solution needed due to a bug in the library 

Non sarà risolto perché si tratta di una soluzione di compromesso necessaria a causa di un bug della libreria
