### ISSUE TITLE
Toast message duplication when exit from a workspace

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#37]
When we click on home icon on the upper right corner to come back on the main page
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/2d12bdbf-1229-429c-892f-4e61e273dca5)
is shown the toast message "Workspace salvato". If we close the message with the X button another (identical) message toast is shown.
Please, remove the second toast message.

![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/656690d3-2bcb-4ae2-a738-28bd80d624e0)

**Comment by MPapini91** [comment]
Remove success message
