### ISSUE TITLE
Error removing file from corpus explorer

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#38]
Removing a file from the corpus presents a problem.
Steps to reproduce the issue:
The corpus must already be populated with at least one folder and one file within the folder as shown in the figure.
1 - open the corpus explorer
2 - try to remove a folder/subfolder
3 - the system will display a toast error message (Error 400: Reference by Resource)
4 - select a file inside the folder that we tried to delete and click on the trash can.
5 - the system does not give any type of error message
6 - by reloading the tree it has not undergone any changes

It seems the interface doesn't call any methods after this situation (checked with browser debug window)

La rimozione  di un file dal corpus presenta un problema.
Passi per riprodurre il problema:
Il corpus deve essere già popolato con almeno un folder e un file all'interno del folder come da figura.
1 - aprire il corpus explorer
2 - tentare di rimuovere un folder/subfolder
3 - il sistema mostrerà un messaggio toast di error (Error 400: Reference by Resource)
4 - selezionare un file all'interno del folder che abbiamo tentato di cancellare e cliccare sul cestino.
5 - il sistema non dà nessun tipo di messaggio di errore
6 - ricaricando l'albero questo non ha subito modifiche

Sembra che l'interfaccia non chiami nessun metodo dopo questa situazione (verificato con la finestra di debug del browser)

![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/f7190a1b-80f4-4a23-8fad-8d76d6c53f8d)

**Comment by MPapini91** [comment]
@magoafono the folder cannot be removed as it contains another item (@davide-albanesi-ilc confirm?), so it is not exactly an error, rather a decision on the deletion policy needs to be made.
Regarding the file deletion, verification is needed, but was the file properly uploaded or did it give an error message when uploading?

@magoafono la cartella non può essere rimossa in quanto contiene un altro elemento (@davide-albanesi-ilc confermi?), quindi non è esattamente un errore, piuttosto si deve prendere una decisione sulla politica di cancellazione.
Per quanto riguarda la cancellazione del file sono necessarie delle verifiche, ma il file era stato correttamente caricato o in fase di upload aveva dato un messaggio di errore?

**Comment by MPapini91** [comment]
In parte il problema sembra essere duplicato dalla issue #40  (anche in quel caso blocco delle interazioni almeno di refresh a seguito di errore 400)
