### ISSUE TITLE
sense relations boxes width should adapt in size

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/Maia#39]
Current boxes displaying target senses in "semantic relations" tab of Lexicon Editor windos are too small and should adapt in width, see example below:

<img width="486" alt="image" src="https://github.com/klab-ilc-cnr/Maia/assets/55898315/d82268ae-bfb3-432b-9f6f-5efdb3cea880">

**Comment by MPapini91** [comment]
Complete tasks 1 and 3 from issue #43 related to render inferred relations

**Comment by MPapini91** [comment]
Step 3 of #43 

![Image](https://github.com/klab-ilc-cnr/Maia/assets/61142119/2a054168-7d44-4f42-bba8-e4cbd88dc5d8)

@andreabellandi we need to check the indirect relationships of lexical items, currently they always seem to be inferred
