### ISSUE TITLE
Error 400 creating new user

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#4]
There is an issue creating a new user.
Step to reproduce:
0 - connect to maia-compl-it-new (URL removed)
1 - login as admin
2 - select User management from menu
3 - click New User
4 - enter Username, password, confirm password,  name, surname,
5 - select row (ADMINISTRATOR)
6 - Select Languages (Italiano)
7 - click on Save

Generated request:
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/3ccaff6a-6b05-4c97-8061-89c1f8bc0879)

Error (400) in console
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/68ec112b-622d-4ef4-b947-7a5099fc9806)

**Comment by magoafono** [comment]
Note: the field email is mandatory.

**Comment by MPapini91** [comment]
- [ ] Set the email field as required for creating a new user
