### ISSUE TITLE
Unable to update tree in Corpus Explorer after an error 400 

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#40]
After a 400 error (caused for example by an illegal deletion such as deleting a non-empty folder) the refresh key no longer invokes the method for reloading the tree

Dopo un errore 400 (causato ad esempio da una cancellazione non consentita come l'eliminazione di una cartella non vuota) il tasto refresh non invoca più il metodo per il ricaricamento dell'albero

Step to reproduce the issue:
1 - open the corpus explorer
2 - create a folder A
3 - create a folder B inside A
4 - try to delete A. Get the 400 error
5 - try to reload the tree with the relative icon 
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/0dd42649-6ae0-4d6b-87b6-e0690707900f)
6 - any other actions on tree (adding folder or file or move them) don't apparently update the tree

**Comment by MPapini91** [comment]
Linked to #38
