### ISSUE TITLE
Annotation sometimes not appearing 

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/Maia#48]
Sometimes, when opening the workspace containing an open annotated text, annotations do not show up: moving to the following page (for example) and going back make the annotations appear again.

![image](https://github.com/MPapini91/maia-fe/assets/55898315/7c4402d1-018e-491a-a92a-287b91036715)

**Comment by cienco** [comment]
Pagination is being substituded by infinite scroll, I cannot see the problem happening anymore, I'm closing this issue.
