### ISSUE TITLE
delete of a set of forms/senses not working and no message received

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/Maia#55]
If I try to delete a whole set of forms or senses **without opening the relative subtree** nothing happens: nor a warning appear, neither forms are deleted

![image](https://github.com/klab-ilc-cnr/maia-fe/assets/55898315/80309598-ec4d-49ee-92f4-4fc47717cff2)

**Comment by MPapini91** [comment]
Il comportamento di cancellazione è stato modificato e la issue non risulta più pertinente
