### ISSUE TITLE
Modification of text management

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#60]
The return JSON of the text retrieval method (POST `/maia/texto/resource/${id}/rows`) must also contain for each line the identifier and the information to be displayed as an index (for example, in the Decameron case "X.1.2")

Il JSON di ritorno del metodo di recupero del testo (POST /maia/texto/resource/${id}/rows) deve contenere per ogni riga anche l'identificativo e l'informazione da visualizzare come indice (per esempio, nel caso Decameron "X.1.2")

**Comment by davide-albanesi-ilc** [comment]
The service now returns additional information for each line. Offsets have start included and end excluded, and start from 0.
    "id": database identifier of the row
    "index": section index
    "absolute": absolute line number (starting from 0)
    "relative": line number relative to the section (starting from 0)
    "start": starting character
    "end": ending character (excluded)
    "text": line text

Il servizio adesso restituisce le informazioni aggiuntive per ogni riga: Gli offset hanno start incluso e end escluso e partono da 0.
    "id": identificativo nel database della riga,
    "index": indice della sezione
    "absolute": numero di riga assoluto (partendo da 0)
    "relative": numero di riga relativo alla sezione (partendo da 0)
    "start": carattere iniziale
    "end": carattere finale (escluso)
    "text": testo della riga
