### ISSUE TITLE
development of the new search panel

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#65]
The search window consists of 2 main parts: 

- [x] #66
- [x] #67

![Image](https://github.com/klab-ilc-cnr/Maia/assets/61142119/c2526dd6-b813-4b00-be3c-7d719bbd5549)

**Comment by cienco** [comment]
I will send a POST request with the following data:

{
  start!: number // for pagination first index element to show
  end!: number;// for pagination last index element to show (end not included)
  selectedResourcesIds: []; //ids of the documents selected in the search filter
  filters :  {
                searchValue!: string // search input value
                searchMode!: string; // values can be 'lemma' or 'form'
                contextLength!: // positive number represents number of words for context
                index?: string // index column filter
                kwic?: string; // keywork column filter
                leftContext?: string; // leftcontext column filter
                rightContext?: string; // rightContext column filter
                text?: string; // text column filter
                textHeader?: string; // ref column filter
              }
}

**Comment by cienco** [comment]
I expect to receive a response with following data, if the property is mandatory is marked with '!' for properties of type string please send me empty string never a null value:

{
    /**number of total elements */
    totalRecords!:number;

    /**row results data*/
    data!: {
    /**string id of the search result this can be the index plus some string es. 'id_1000'*/
    id!:string;

    /**index of the search result element to show in the column*/
    index!: number;

    /**the index of the row in the document body (that will be opened on click)*/
    rowIndex!: number;

    /**document name */
    text!: string;

    /**document id */
    textId!: number;

    /**the corpus index (ref. in the mockup example) */
    textHeader?: string';

    /**partial text to show before */
    leftContext!: string;

    /**partial text to show after */
    rightContext: string;

    /**keyword */
    kwic!: string;
}
}
