### ISSUE TITLE
References to target senses in semantic relations tab should include the lemma before the definition

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/Maia#7]
As title.

<img width="960" alt="image" src="https://github.com/klab-ilc-cnr/Maia/assets/55898315/8f15246b-fcd7-4a55-a13c-ee7151fef6bc">

**Comment by MPapini91** [comment]
format: 
**lemma**: definition

Both for options and selcted value

**Comment by cienco** [comment]
The lemma is missing in the response from the API that takes the string to show to the user. You can just see it when you search for a new word because the string given from the other API is used temporary to fill the textbox and it contains the lemma.

**Comment by andreabellandi** [comment]
For direct sense relations: the lemma with its language is contained in the "label" field (e.g., "label" : "waran@som - Wadarta ereyga waran")

For indirect sense relations: the lemma with its language is contained in the "targetLexicalEntry" field

**Comment by cienco** [comment]
@tarnisil @andreabellandi the new label format is of the type "alool@som - Wadarta ereyga alool" if it's the right format we can close this issue

**Comment by andreabellandi** [comment]
it's fine for me!

**Comment by tarnisil** [comment]
fine for me too, thx!
