### ISSUE TITLE
CPU usage in Text panel

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#76]
Having experienced slowdowns working with the text annotation panel, we did some testing to identify the problem. Using Chrome's Performance monitor, we saw that in any text, if I just move the mouse over the SVG the CPU usage goes up to 100%. This behavior is obviously not desired; further analysis is needed to solve the problem.

![WhatsApp Image 2024-03-20 at 15 24 37_d42eaeae](https://github.com/klab-ilc-cnr/Maia/assets/61142119/c2801c29-85c6-4960-8d08-df3a0b8e9e92)

######################################

Avendo riscontrato dei rallentamenti lavorando con il pannello di annotazione del testo, abbiamo fatto alcune verifiche per identificare il problema. Utilizzando il Performance monitor di Chrome, abbiamo visto che, in un qualsiasi testo, se mi limito a muovere il mouse sopra l'SVG l'utilizzo della CPU sale fino al 100%. Questo comportamento ovviamente non è desiderato, è necessario approfondire le analisi per la risoluzione del problema.

**Comment by MPapini91** [comment]
Temporary fix removing mouse events

**Comment by MPapini91** [comment]
Persiste il problema del carico della CPU durante il rendering di un testo fortemente annotato come quelli pre-caricati sulla macchina di test. La causa sembra essere un evento di mouseout (del quale però non siamo riusciti a ricavare l'origine). Vi chiediamo di indagare ulteriormente la issue.

**Comment by cienco** [comment]
L'evento di mouseout non è legato a uno sviluppo specifico fatto da noi ma fa parte dei meccanismi di change detection che sono alla base di angular attraverso con l'uso combinato della libreria zone.js. Un'applicazione web per l'annotazione di testi che simula il comportamento di un sistema desktop a finestre attraverso un browser porta con se inevitabilmente dei problemi di performance non banalmente superabili.
