### ISSUE TITLE
Error modifying morphological traits

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#78]
Quando si tenta di modificare un tratto morfologico precedentemente inserito il sistema si genera il seguente errore.
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/6059afa2-7e2a-4bf3-a810-1d2f5005e4a0)
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/e4d937d0-2222-46b1-b078-d54c1d03ff3e)
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/ee1b4d09-73ee-484f-b7cf-b4f30009aa44)

Il problema è causato dal fatto che è necessario modificare entrambi i valori sia la relation che il value.

**Comment by MPapini91** [comment]
Come workaround alla selezione di un tratto il primo dropdown viene disabilitato. L'utente per modificarlo deve rimuoverlo. Soluzione non ottimale, ma permette di mantenere la consistenza dei dati
