### ISSUE TITLE
Console message: type LEXICON_EDIT not implemented

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#80]
As title
![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/409ed7b4-8d86-4e5d-9db5-f8b0b18e48a5)

Qual è il significato?

**Comment by MPapini91** [comment]
The panel type LEXICON_EDIT is not mapped to back-end and is in fact not stored (location etc) when reopening a workspace. It must be added and properly managed, just as it was done for the other panel types. 
Davide is a backend side intervention required for this? You should have already run into the same situation for the SEARCH type.

###############################################

Il tipo di pannello LEXICON_EDIT non è mappato a back-end e non viene infatti memorizzato (posizione etc) quando si riapre un workspace. Deve essere aggiunto e correttamente gestito, così come è stato fatto per gli altri tipi di pannello. 
@davide-albanesi-ilc  è necessario un intervento lato backend per questo? Dovresti essere già incappato nella stessa situazione per il tipo SEARCH.

**Comment by davide-albanesi-ilc** [comment]
LEXICON_EDIT is now mapped to database

**Comment by MPapini91** [comment]
One front-end change (code uncommenting) is missing to complete the issue resolution
