### ISSUE TITLE
Problemi nella visualizzazione della finestra di testo.

### ISSUE THREAD

**Issue by magoafono** [klab-ilc-cnr/Maia#82]
La visualizzazione iniziale delle 3 sezioni della finestra di testo  va rivista.
In particolare la colonna delle annotazioni collassata è troppo grande. Deve apparire, inizialmente, larga circa come la dimensione della icona di annotazione ![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/7ca9c4ac-d736-4708-bc48-4a874bed2b84)
Inoltre non è possibile ridimensionare in larghezza la colonna centrale (o visualizzatore del testo) affinché la colonna di destra si riduca come richiesto.
Ancora, cliccando sulla icona per collassare la colonna di sinistra (o albero di navigazione) questa non viene ridotta nella sua larghezza.
Non si può modificare la larghezza con l'apposito handle e, inoltre, viene scatenato l'evento di apertura dell'albero che dovrebbe essere associato al solo click sulla icona ![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/92d98073-b0be-4c1b-bbfb-cfd28824673f)

![image](https://github.com/klab-ilc-cnr/Maia/assets/10340896/70784300-e10a-46c7-bc4e-964d15af9971)

**Comment by cienco** [comment]
Il comportamento che descrivi non è voluto, ma non riesco a riprodurlo (forse usi una versione più vecchia dell'applicazione), è possibile che l'abbia già sistemato durante i miei test e fix. Potresti riprovare con l'ultima versione di sviluppo disponibile e se il problema si presenta ancora indicarmi con quale browser stai facendo il test.

**Comment by MPapini91** [comment]
@cienco non ho l'esatta sequenza che ha causato l'evento, ma ho ridimensionato la finestra del browser e il pannello, a un certo punto mi sono resa conto che la colonna era sballata. La versione dell'applicazione è la più recente (sto eseguendo in locale il mio branch 84  che integra lo stato del develop).

Chrome è aggiornato
Versione 124.0.6367.119 (Build ufficiale) (a 64 bit)

<img width="1514" alt="image" src="https://github.com/klab-ilc-cnr/Maia/assets/61142119/16c3b77e-3b32-4855-a3b2-71f24e88dc1e">

**Comment by cienco** [comment]
Non riesco a riprodurlo @MPapini91 potresti provare a riprodurre il problema e salvare un workspace apposito, sempre che alla riapertura il problema persista, il che non è certo.

**Comment by cienco** [comment]
è un problema di interazioni di stili sovrascritti globalmente da ngdeep da altri componenti come il lexicon editor, il problema era replicabile aprendo appunto la finestra di lexicon editor e successivamente la finestra di testo.
