### ISSUE TITLE
Deletion of a document from the corpus

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#87]
Maia must allow deletion of a document from the corpus, currently the deletion service, on an unannotated (newly uploaded) text returns the following error message:

 ```
{
    "timestamp": "2024-04-15T10:37:41.125+00:00",
    "status": 500,
    "error": "internal server error",
    "message": "400 : \"referenced by Row\"",
    "path":"/maia/texto/resource/32597/remove"
}
```

#############################

Maia deve consentire di cancellare un documento dal corpus, attualmente il servizio di cancellazione, su un testo non annotato (appena caricato) restituisce il seguente messaggio di errore:

```
 {
    "timestamp": "2024-04-15T10:37:41.125+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "400 : \"referenced by Row\"",
    "path": "/maia/texto/resource/32597/remove"
}
```

**Comment by davide-albanesi-ilc** [comment]
Implementata la rimozione a cascata delle strutture dati ausiliarie relative ad una risorsa che ne impedivano la rimozione

**Comment by MPapini91** [comment]
@davide-albanesi-ilc la cancellazione di un documento dal corpus restituisce l'errore:
```
{
    "timestamp": "2024-07-16T09:32:21.054+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "500 : \"{\"timestamp\":\"2024-07-16T09:32:21.050+00:00\",\"status\":500,\"error\":\"Internal Server Error\",\"path\":\"/texto/resource/20091920/remove\"}\"",
    "path": "/maia/texto/resource/20091920/remove"
}
```
