### ISSUE TITLE
Resizing KWIC table columns

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#89]
Le colonne devono essere ridimensionate in apertura come segue (si faccia riferimento all'immagine come esempio):

- 40% circa dell'ampiezza per le seguenti colonne
   - colonna checkbox ridotta alla dimensione della checkbox stessa (considerandoi un minimo di padding)
   - colonna index calcolata sulla dimensione massima che può assumere l'incrementale per quella ricerca
   - colonna text e colonna ref si suddividono lo spazio rimanente (compatibilmente con il loro contenuto)
- circa il 60% dell'ampiezza totale deve essere occupata dalle colonne left context, kwic e right context
   - colonna KWIC con ampiezza dipendente dal contenuto
   - colonne left e right context si suddividono equamente l'ampiezza residua

![image](https://github.com/klab-ilc-cnr/Maia/assets/61142119/54b7e7bd-54ab-4056-bcd9-847d4872342e)

**Comment by cienco** [comment]
Ho rispettato le proporzioni del 40 e del 60 percento tuttavia il componente primeng di per se non permette tutte queste combinazioni dinamiche e diventa rischioso andare a comprometterne il funzionamento interno. Credo di essere comunque riuscito a trovare una via di mezzo soddisfacente considerando che le colonne sono comunque ridimensionabili e in una buona percentuale di casi le dimensioni iniziali scelte dovrebbero essere soddisfacenti.
