### ISSUE TITLE
Resizing KWIC table on panel resize

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#90]
Collegata alla issue #89 
Quando modifico la larghezza del pannello di Search, la dimensione delle colonne non viene ricalcolata dinamicamente. Vedi esempio in immagine, allargando il pannello utilizzato per l'esempio della issue 89, rimane dello spazio bianco a destra. Analogamente quando restringo (entro la larghezza minima impostata) mi aspetto che le colonne si adattino.

![image](https://github.com/klab-ilc-cnr/Maia/assets/61142119/b9db5a67-0a9e-49f9-aa65-dc01930a686e)

Facendo qualche prova per simulare il comportamento corretto da browser ho visto che modificando la width da px a % sembrava funzionare (anche se ovviamente la modifica nel progetto non  credo sia immediata). Riporto lo screen del punto
![image](https://github.com/klab-ilc-cnr/Maia/assets/61142119/54e65a2b-b04e-4abd-a7fc-1ee1d1c8c4f9)

**Comment by cienco** [comment]
Primeng di per se non permette di farlo a meno che non si utilizzi la modalità di ridemensionamento di tipo 'fit', in ogni caso ho provato a inserire una soluzione intermedia che ridimensiona le colonne in modo dinamico quando avviene il resize del pannello.
