### ISSUE TITLE
Change behavior retrieval annotations

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#92]
Il nuovo comportamento in apertura di un testo deve prevedere che non siano selezionati e recuperati di default tutti i possibili layer di annotazione. Sono quindi necessari due macro-interventi:

- [x] modifica servizio maia/texto/util/resource/{id}/annotations --> aggiungere al json di richiesta la possibilità di passare l'elenco degli id dei layer dei quali recuperare le annotazioni
- [x] #98

Cioè  la modifica dell'interfaccia affinché passi al back-end l'elenco dei layer dei quali recuperare le annotazioni

**Comment by davide-albanesi-ilc** [comment]
Aggiunto il campo "layers" al json della richiesta. Questo campo contiene la lista di id dei layers. Se layers è nullo o vuoto il filtro non viene applicato e verranno restituite le annotazioni di tutti i layers.
Es.: {"layers":[8, 11], "start":0,"end":20}
