### ISSUE TITLE
Storage in the layout of the Dictionary panels

### ISSUE THREAD

**Issue by MPapini91** [klab-ilc-cnr/Maia#93]
Information must be stored in maia-be in order to reopen the Dictionary Explorer and Dictionary Editor panels.  The types provided are DICTIONARY and DICTIONARY_EDIT, respectively, analogous to what was done for the lexicon (see also issue [80](https://github.com/klab-ilc-cnr/Maia/issues/80)).
For DICTIONARY_EDIT it will be necessary to expect a `content: {contentId: 'dictionary_id'}`

###################################

In maia-be devono essere memorizzate le informazioni per poter riaprire i pannelli del Dictionary Explorer e del Dictionary Editor.  I tipi previsti sono rispettivamente DICTIONARY e DICTIONARY_EDIT, in analogia con quanto fatto per il lessico (vedi anche la issue [80](https://github.com/klab-ilc-cnr/Maia/issues/80)).
Per DICTIONARY_EDIT sarà necessario prevedere un `content: {contentId: 'dictionary_id'}`

**Comment by davide-albanesi-ilc** [comment]
DICTIONARY and DICTIONARY_EDIT are now mapped to database. For DICTIONARY_EDIT you can store the `contentId` value.
