### ISSUE TITLE
Selection of "Layer" must imply visibility of that layer

### ISSUE THREAD

**Issue by tarnisil** [klab-ilc-cnr/Maia#99]
Each time a user selects a "Layer" in the Text window the relative layer "Visibility" should automatically turn on

![image](https://github.com/klab-ilc-cnr/Maia/assets/55898315/dae00b5b-b407-479d-93bb-adbc8c3f7d63)

**Comment by MPapini91** [comment]
In caso di selezione di un Layer per l'annotazione, questo dovrà essere aggiunto ai layer precedentemente selezionati in Visibility (se non già selezionato).
